#!/usr/bin/perl
=head1 Pulma passwords generator

Part of Pulma system

Script to calculate password hash using built-in algorithm

Copyright (C) 2011 Fedor A. Fetisov <faf@ossg.ru>. All Rights Reserved

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License

=cut

use strict;
use warnings;

use lib '../';

use Pulma::Service::Functions;

use Pod::Usage;

=head1 Usage

=over

=item calculate_password_hash <username> <password>

=back

=cut

my ($username, $password) = @ARGV;

unless (defined $username && defined $password) {

    pod2usage(-exitval => 1, -verbose => 2);

}

print calculate_password_hash($username, $password);
print "\n";
