#!/bin/sh
#
# pulma - Spawn Pulma FastCGI application
#
# chkconfig: - 48 52
# description:	Start FastCGI server of Pulma system
# processname: pulma
#
# Part of Pulma system
#
# init.d script to start Pulma FastCGI server
#
# Copyright (C) 2011 Fedor A. Fetisov <faf@ossg.ru>. All Rights Reserved
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

# Do not load RH compatibility interface.
WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/init.d/functions

DISPLAYNAME=pulma
NAME=perl

LOCKFILE=/opt/pulma/var/lock/subsys/pulma
PIDFILE=/opt/pulma/var/run/pulma/pulma.pid
BASEDIR=/opt/pulma
EXECFILE=$BASEDIR/pulma
CONFIG_FILE=$BASEDIR/pulma.conf
DAEMONUSER=root
CGIUSER=_nginx

RETVAL=0

start()
{
	start_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --user "$DAEMONUSER" --displayname "$DISPLAYNAME" --expect-user "$CGIUSER" -- "$EXECFILE" "$CONFIG_FILE"
	RETVAL=$?
}

stop()
{
	stop_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user "$CGIUSER" --displayname "$DISPLAYNAME" -- "$NAME"
	RETVAL=$?
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
                stop
		;;
	restart)
		stop
		start
		;;
	status)
		status --displayname "$DISPLAYNAME" --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user "$CGIUSER" $NAME
		RETVAL=$?
		;;
	*)
		msg_usage "${0##*/} {start|stop|restart|status}"
		RETVAL=1
esac

exit $RETVAL
